name: run-examples
run-name: run examples
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: gcc
      - name: Check GHDL version    
        run: ghdl --version
