name: run-examples
run-name: run examples
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages
        run: sudo apt-get install ghdl-gcc verilator
      - name: Check GHDL version    
        run: ghdl --version
      - name: Check Verilator version    
        run: verilator --version
      - name: run example vhd_v_counter
        run: make -C examples/vhd_v_counter
      - name: run example m-labs-lm32
        run: make -C examples/m-labs-lm32
      - name: run example two_modules
        run: make -C examples/two_modules
      - name: run example serv
        run: make -C examples/serv
      - name: run example ibex
        run: make -C examples/ibex
